<?php

/**
 * @file
 * Functions to support theming in the Localgov Gov.UK theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function localgov_govuk_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function localgov_govuk_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function localgov_govuk_preprocess_node(&$variables) {

}
